package com.heaton.funnyvote.analytics

/**
 * Created by heaton on 2017/3/5.
 */

object AnalyzticsTag {
    val SCREEN_MAIN = "MAIN"
    val SCREEN_MAIN_HOT = "MAIN_HOT"
    val SCREEN_MAIN_NEW = "MAIN_NEW"

    val SCREEN_CREATE_VOTE = "CREATE_VOTE"
    val SCREEN_CREATE_VOTE_OPTIONS = "CREATE_VOTE_OPTIONS"
    val SCREEN_CREATE_VOTE_SETTINGS = "CREATE_VOTE_SETTINGS"

    val SCREEN_BOX = "BOX"
    val SCREEN_BOX_CREATE = "BOX_CREATE"
    val SCREEN_BOX_PARTICIPATE = "BOX_PARTICIPATE"
    val SCREEN_BOX_FAVORITE = "BOX_FAVORITE"

    val SCREEN_PERSONAL = "PERSONAL"
    val SCREEN_PERSONAL_CREATE = "PERSONAL_CREATE"
    val SCREEN_PERSONAL_FAVORITE = "PERSONAL_FAVORITE"

    val SCREEN_SEARCH = "SEARCH"

    val SCREEN_ACCOUNT = "ACCOUNT"

    val SCREEN_ABOUT = "ABOUT"
    val SCREEN_ABOUT_FUNNYVOTE_APP = "ABOUT_FUNNYVOTE_APP"
    val SCREEN_ABOUT_AUTHOR = "ABOUT_AUTHOR"
    val SCREEN_ABOUT_LICENCE = "ABOUT_LICENCE"
    val SCREEN_ABOUT_PROBLEM = "ABOUT_PROBLEM"
    val SCREEN_ABOUT_SHARE_APP = "ABOUT_SHARE_APP"
    val SCREEN_ABOUT_UPDATE_APP = "ABOUT_UPDATE_APP"


    val SCREEN_APP_INTRO = "APP_INTRO"
    val SCREEN_APP_INTRO_FUNNYVOTE = "APP_INTRO_FUNNYVOTE"
    val SCREEN_APP_INTRO_QUICKPOLL = "APP_INTRO_QUICKPOLL"
    val SCREEN_APP_INTRO_NO_COMMENT = "APP_INTRO_NO_COMMENT"
    val SCREEN_APP_INTRO_BIGDATA = "APP_INTRO_BIG_DATA"
    val SCREEN_APP_INTRO_SHARE_FIN = "APP_INTRO_SHARE_FIN"
    val SCREEN_APP_INTRO_COME = "APP_INTRO_COME"

    val SCREEN_VOTE_DETAIL = "VOTE_DETAIL"

    val SCREEN_SHARE_VOTE = "SHARE_VOTE"

    val ACTION_POLL_VOTE = "POLL_VOTE"
    val ACTION_QUICK_POLL_VOTE = "QUICK_POLL_VOTE"
    val ACTION_ENTER_VOTE = "ENTER_VOTE"
    val ACTION_LINK_VOTE = "LINK_VOTE"
    val ACTION_SEARCH_VOTE = "SEARCH_VOTE"
    val ACTION_ADD_FAVORITE = "ADD_FAVORITE_VOTE"
    val ACTION_REMOVE_FAVORITE = "REMOVE_FAVORITE_VOTE"
    val ACTION_SHARE_VOTE = "SHARE_VOTE"
    val ACTION_SEARCH_OPTION = "SEARCH_OPTION"
    val ACTION_MOVE_TOP = "MOVE_TOP"
    val ACTION_CHANGE_MODE = "CHANGE_MODE"
    val ACTION_ADD_NEW_OPTION = "ADD_NEW_OPTION"

    val ACTION_ENTER_PERSONAL_INFO = "ENTER_PERSONAL_INFO"
    val ACTION_ENTER_USER_INFO = "ENTER_USER_INFO"

    val ACTION_CLICK_PROMOTION = "CLICK_PROMOTION"

    val ACTION_CREATE_VOTE = "CREATE_VOTE"

    val ACTION_ACCOUNT_LOGIN = "ACCOUNT_LOGIN"
    val ACTION_ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT"
    val ACTION_ACCOUNT_RENAME = "ACCOUNT_RENAME"

    val ACTION_SHARE_APP = "SHARE_APP"

    val CATEGORY_PROMOTION = "PROMOTION"
    val CATEGORY_ADMOB = "ADMOB"

    val CATEGORY_VOTE_DETAIL = "VOTE_DETAIL"
    val CATEGORY_SEARCH_VOTE = "SEARCH_VOTE"
    val CATEGORY_CREATE_VOTE = "CREATE_VOTE"
    val CATEGORY_PERSONAL = "PERSONAL_INFO"
    val CATEGORY_USER = "USER_INFO"
    val CATEGORY_ACCOUNT = "ACCOUNT"

}
